import { Theme } from "theme.slint";
import { Header } from "header.slint";

export component Panel2Display inherits Window {
    width: 240px;
    height: 284px;

    default-font-family: "Inter";
    background: Theme.background-color;

    // ─────────────────────────────────────────────
    // Values
    // ─────────────────────────────────────────────

    in property <string> sensor-status: "X6 CONNECTED";

    // ═════════════════════════════════════════════
    // Outer display ring
    // ═════════════════════════════════════════════

    Rectangle {
        x: 0px;
        y: 0px;
        width: 240px;
        height: 284px;

        border-radius: 45px;
        background: transparent;

        border-width: 3px;
        border-color: #2d3035;
    }

    Header {
        x: 0px;
        y: 0px;

        status: sensor-status;
    }

    property <int> frame: 0;
    property <int> frame-count: 30;

    Timer {
        interval: 33ms;
        running: true;
        triggered => {
            root.frame = Math.mod(root.frame + 1, root.frame-count);
        }
    }

    Image {
        x: (root.width - self.width) / 2;
        y: 90px;
        width: 200px;
        height: 200px;

        source: @image-url("../icons/toyota_anim.png");
        source-clip-x: root.frame * 200;
        source-clip-y: 0;
        source-clip-width: 200;
        source-clip-height: 200;
    }
}
