// The palette, in one place.

export global Theme {
    out property <color> background-color: #000000;
    out property <color> text-main: #ffffff;
    out property <color> text-secondary: #416788;
    out property <color> accent-color: #55D6BE;
    out property <color> thermometer-tint: #55D6BE;
    out property <color> humidity-tint: #4C86A8;
    out property <color> pressure-tint: #DBBBF5;
}
