//! Bring up one 1.83" ST7789 panel and drive a Slint UI on it.

use std::{
    ops::Range,
    rc::Rc,
    time::{Duration, Instant},
};

use embedded_graphics::draw_target::DrawTarget;
use embedded_graphics::pixelcolor::{Rgb565, raw::RawU16};
use embedded_graphics::prelude::RgbColor;
use esp_idf_svc::{
    hal::{
        delay::{Ets, FreeRtos},
        gpio::{AnyInputPin, PinDriver},
        peripherals::Peripherals,
        spi::{
            SpiDeviceDriver, SpiDriverConfig,
            config::{Config as SpiConfig, MODE_3},
        },
        units::FromValueType,
    },
    sys::EspError,
};
use log::{error, info};
use mipidsi::{Builder, interface::SpiInterface, models::ST7789, options::ColorInversion};
use slint::{
    ComponentHandle, PhysicalSize, PlatformError,
    platform::{
        Platform, WindowAdapter,
        software_renderer::{
            LineBufferProvider, MinimalSoftwareWindow, RepaintBufferType, Rgb565Pixel,
        },
    },
};

/// Rust side of `assets/credit_dashboard.slint`, generated by `build.rs`.
// Generated code: the workspace's doc and pedantic lints aren't ours to satisfy there.
#[allow(missing_docs, unreachable_pub, unused_qualifications, clippy::pedantic)]
mod ui {
    slint::include_modules!();
}

/// Visible width in pixels, portrait.
const WIDTH: u16 = 240;

/// Visible height in pixels.
const HEIGHT: u16 = 320;

/// Why bring-up failed.
#[derive(Debug)]
enum Error {
    /// ESP-IDF refused a driver: the SPI bus or a GPIO.
    Esp(EspError),
    /// The panel failed to init or draw. mipidsi's errors only implement `Debug`.
    Panel(String),
    /// Slint refused the platform, or the UI failed to build.
    Ui(String),
}

impl From<EspError> for Error {
    fn from(e: EspError) -> Self {
        Self::Esp(e)
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Esp(e) => write!(f, "esp-idf: {e}"),
            Self::Panel(msg) => write!(f, "panel: {msg}"),
            Self::Ui(msg) => write!(f, "ui: {msg}"),
        }
    }
}

/// Slint's view of the board: one fixed window and a clock.
struct Board {
    /// The only window; Slint asks for it once, when the UI is created.
    window: Rc<MinimalSoftwareWindow>,
    /// Boot time, the zero for Slint's timers and animations.
    start: Instant,
}

impl Platform for Board {
    fn create_window_adapter(&self) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
        Ok(self.window.clone())
    }

    fn duration_since_start(&self) -> Duration {
        self.start.elapsed()
    }
}

/// Lends Slint one panel row at a time, then hands the rendered part to `push`.
struct LineSink<F> {
    /// One panel row; Slint renders into the dirty part of it.
    buffer: Vec<Rgb565Pixel>,
    /// Receives the row index, the dirty column range, and its pixels.
    push: F,
}

impl<F: FnMut(usize, Range<usize>, &[Rgb565Pixel])> LineBufferProvider for LineSink<F> {
    type TargetPixel = Rgb565Pixel;

    fn process_line(
        &mut self,
        line: usize,
        range: Range<usize>,
        render_fn: impl FnOnce(&mut [Self::TargetPixel]),
    ) {
        let pixels = &mut self.buffer[range.clone()];
        render_fn(pixels);
        (self.push)(line, range, pixels);
    }
}

/// Boots, runs the UI, logs why it stopped.
fn main() {
    // Pulls in ESP-IDF runtime patches std relies on; must run before anything else.
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();

    if let Err(e) = run() {
        error!("ui stopped: {e}");
    }
}

/// Brings the panel up, then renders the UI forever, holding every driver alive.
///
/// Only returns on error: dropping a `PinDriver` resets its pin, which would
/// switch the backlight off the moment this function ended.
fn run() -> Result<(), Error> {
    let peripherals = Peripherals::take()?;
    let pins = peripherals.pins;

    // Backlight stays off until the panel holds a real frame — no garbage at boot.
    let mut backlight = PinDriver::output(pins.gpio6)?;
    backlight.set_low()?;
    let dc = PinDriver::output(pins.gpio22)?;
    let rst = PinDriver::output(pins.gpio23)?;

    // 10 MHz while bringing it up; raise once colours look clean.
    // No MISO: the panel never talks back.
    let spi = SpiDeviceDriver::new_single(
        peripherals.spi2,
        pins.gpio20, // CLK
        pins.gpio21, // DIN
        None::<AnyInputPin<'_>>,
        Some(pins.gpio5), // CS
        &SpiDriverConfig::new(),
        &SpiConfig::new().baudrate(10.MHz().into()).data_mode(MODE_3),
    )?;

    // Pixels are batched here before each SPI write.
    let mut buffer = [0_u8; 512];
    let di = SpiInterface::new(spi, dc, &mut buffer);

    let mut display = Builder::new(ST7789, di)
        // IPS ST7789 panels show a negative image without this.
        .invert_colors(ColorInversion::Inverted)
        .reset_pin(rst)
        .init(&mut Ets)
        .map_err(|e| Error::Panel(format!("init: {e:?}")))?;

    // Black over the whole RAM: every row the glass can show gets written,
    // so no power-on noise survives outside the visible window.

    display
        .clear(Rgb565::BLACK)
        .map_err(|e| Error::Panel(format!("clear: {e:?}")))?;

    // `ReusedBuffer`: the panel's RAM keeps the last frame, so Slint only
    // redraws what changed.
    let window = MinimalSoftwareWindow::new(RepaintBufferType::ReusedBuffer);
    window.set_size(PhysicalSize::new(WIDTH.into(), HEIGHT.into()));
    slint::platform::set_platform(Box::new(Board {
        window: window.clone(),
        start: Instant::now(),
    }))
    .map_err(|e| Error::Ui(format!("platform: {e:?}")))?;

    let ui = ui::CreditScreen::new().map_err(|e| Error::Ui(format!("create: {e}")))?;
    ui.show().map_err(|e| Error::Ui(format!("show: {e}")))?;

    let mut lit = false;

    loop {
        slint::platform::update_timers_and_animations();

        // `process_line` can't return an error, so the first one is parked here.
        let mut failed = None;
        window.draw_if_needed(|renderer| {
            renderer.render_by_line(LineSink {
                buffer: vec![Rgb565Pixel::default(); usize::from(WIDTH)],
                push: |line, range: Range<usize>, pixels: &[Rgb565Pixel]| {
                    if range.is_empty() {
                        return;
                    }
                    let (Ok(x0), Ok(x1), Ok(y)) = (
                        u16::try_from(range.start),
                        u16::try_from(range.end - 1),
                        u16::try_from(line),
                    ) else {
                        return;
                    };
                    // Same 565 bit layout on both sides; mipidsi does the byte order.
                    let colors = pixels.iter().map(|p| Rgb565::from(RawU16::new(p.0)));
                    // `set_pixels` takes inclusive end coordinates.
                    if let Err(e) = display.set_pixels(x0, y, x1, y, colors) {
                        failed.get_or_insert(format!("line {line}: {e:?}"));
                    }
                },
            });
        });
        if let Some(msg) = failed {
            return Err(Error::Panel(msg));
        }

        if !lit {
            backlight.set_high()?;
            lit = true;
            info!("first frame drawn");
        }

        // Animations need frames; otherwise idle at ~60 Hz polling.
        if !window.has_active_animations() {
            FreeRtos::delay_ms(16);
        }
    }
}
