//! Bring up two 1.83" ST7789 panels on one SPI bus and drive a Slint UI on each.

use std::{
    cell::Cell,
    ops::Range,
    rc::Rc,
    time::{Duration, Instant},
};

use embedded_graphics::draw_target::DrawTarget;
use embedded_graphics::pixelcolor::{Rgb565, raw::RawU16};
use embedded_graphics::prelude::RgbColor;
use esp_idf_svc::{
    hal::{
        delay::{Ets, FreeRtos},
        gpio::{AnyInputPin, Output, PinDriver},
        peripherals::Peripherals,
        spi::{
            SpiDeviceDriver, SpiDriver, SpiDriverConfig,
            config::{Config as SpiConfig, MODE_3},
        },
        units::FromValueType,
    },
    sys::EspError,
};
use log::{error, info};
use mipidsi::{Builder, interface::SpiInterface, models::ST7789, options::ColorInversion};
use slint::{
    ComponentHandle, PhysicalSize, PlatformError,
    platform::{
        Platform, WindowAdapter,
        software_renderer::{
            LineBufferProvider, MinimalSoftwareWindow, RepaintBufferType, Rgb565Pixel,
        },
    },
};

/// Rust side of `assets/ui.slint`, generated by `build.rs`.
// Generated code: the workspace's doc and pedantic lints aren't ours to satisfy there.
#[allow(
    missing_debug_implementations,
    missing_docs,
    unreachable_pub,
    unused_qualifications,
    clippy::pedantic
)]
mod ui {
    slint::include_modules!();
}

/// Visible width in pixels, portrait.
const WIDTH: u16 = 240;

/// Visible height in pixels.
const HEIGHT: u16 = 320;

/// How many panels hang off the shared SPI2 bus.
const PANELS: usize = 2;

/// One ST7789 on the shared bus, with its own D/C and reset pins.
///
/// Both panels land on this exact type: `PinDriver` erases the pin it drives,
/// and both SPI devices borrow the same `SpiDriver`.
type Panel<'d> = mipidsi::Display<
    SpiInterface<'d, SpiDeviceDriver<'d, &'d SpiDriver<'d>>, PinDriver<'d, Output>>,
    ST7789,
    PinDriver<'d, Output>,
>;

/// Why bring-up failed.
#[derive(Debug)]
enum Error {
    /// ESP-IDF refused a driver: the SPI bus or a GPIO.
    Esp(EspError),
    /// The panel failed to init or draw. mipidsi's errors only implement `Debug`.
    Panel(String),
    /// Slint refused the platform, or the UI failed to build.
    Ui(String),
}

impl From<EspError> for Error {
    fn from(e: EspError) -> Self {
        Self::Esp(e)
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Esp(e) => write!(f, "esp-idf: {e}"),
            Self::Panel(msg) => write!(f, "panel: {msg}"),
            Self::Ui(msg) => write!(f, "ui: {msg}"),
        }
    }
}

/// Slint's view of the board: one fixed window per panel, and a clock.
struct Board {
    /// One per panel. Slint takes these in order, one per UI that gets created.
    windows: [Rc<MinimalSoftwareWindow>; PANELS],
    /// How many of `windows` Slint has already taken.
    handed_out: Cell<usize>,
    /// Boot time, the zero for Slint's timers and animations.
    start: Instant,
}

impl Platform for Board {
    fn create_window_adapter(&self) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
        let taken = self.handed_out.get();
        let window = self.windows.get(taken).ok_or_else(|| {
            PlatformError::Other(format!(
                "only {PANELS} panels, but UI {taken} asked for a window"
            ))
        })?;
        self.handed_out.set(taken + 1);
        Ok(window.clone())
    }

    fn duration_since_start(&self) -> Duration {
        self.start.elapsed()
    }
}

/// Lends Slint one panel row at a time, then hands the rendered part to `push`.
struct LineSink<F> {
    /// One panel row; Slint renders into the dirty part of it.
    buffer: Vec<Rgb565Pixel>,
    /// Receives the row index, the dirty column range, and its pixels.
    push: F,
}

impl<F: FnMut(usize, Range<usize>, &[Rgb565Pixel])> LineBufferProvider for LineSink<F> {
    type TargetPixel = Rgb565Pixel;

    fn process_line(
        &mut self,
        line: usize,
        range: Range<usize>,
        render_fn: impl FnOnce(&mut [Self::TargetPixel]),
    ) {
        let pixels = &mut self.buffer[range.clone()];
        render_fn(pixels);
        (self.push)(line, range, pixels);
    }
}

/// Renders `window` into `display`, if Slint says it needs a repaint.
fn draw(window: &MinimalSoftwareWindow, display: &mut Panel<'_>) -> Result<(), Error> {
    // `process_line` can't return an error, so the first one is parked here.
    let mut failed = None;
    window.draw_if_needed(|renderer| {
        renderer.render_by_line(LineSink {
            buffer: vec![Rgb565Pixel::default(); usize::from(WIDTH)],
            push: |line, range: Range<usize>, pixels: &[Rgb565Pixel]| {
                if range.is_empty() {
                    return;
                }
                let (Ok(x0), Ok(x1), Ok(y)) = (
                    u16::try_from(range.start),
                    u16::try_from(range.end - 1),
                    u16::try_from(line),
                ) else {
                    return;
                };
                // Same 565 bit layout on both sides; mipidsi does the byte order.
                let colors = pixels.iter().map(|p| Rgb565::from(RawU16::new(p.0)));
                // `set_pixels` takes inclusive end coordinates.
                if let Err(e) = display.set_pixels(x0, y, x1, y, colors) {
                    failed.get_or_insert(format!("line {line}: {e:?}"));
                }
            },
        });
    });
    if let Some(msg) = failed {
        return Err(Error::Panel(msg));
    }
    Ok(())
}

/// Boots, runs the UI, logs why it stopped.
fn main() {
    // Pulls in ESP-IDF runtime patches std relies on; must run before anything else.
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();

    if let Err(e) = run() {
        error!("ui stopped: {e}");
    }
}

/// Brings the panel up, then renders the UI forever, holding every driver alive.
///
/// Only returns on error: dropping a `PinDriver` resets its pin, which would
/// switch the backlight off the moment this function ended.
fn run() -> Result<(), Error> {
    let peripherals = Peripherals::take()?;
    let pins = peripherals.pins;

    // Backlights stay off until the panels hold a real frame — no garbage at boot.
    let mut backlights = [
        PinDriver::output(pins.gpio6)?,
        PinDriver::output(pins.gpio26)?,
    ];
    for backlight in &mut backlights {
        backlight.set_low()?;
    }

    // One bus, shared CLK and DIN. No MISO: the panels never talk back.
    let bus = SpiDriver::new(
        peripherals.spi2,
        pins.gpio20, // CLK
        pins.gpio21, // DIN
        None::<AnyInputPin<'_>>,
        &SpiDriverConfig::new(),
    )?;

    // 10 MHz while bringing them up; raise once colours look clean. Each panel
    // is its own device on the bus, picked out by its own hardware CS.
    let spi_config = SpiConfig::new().baudrate(10.MHz().into()).data_mode(MODE_3);
    let credit_spi = SpiDeviceDriver::new(&bus, Some(pins.gpio5), &spi_config)?;
    let status_spi = SpiDeviceDriver::new(&bus, Some(pins.gpio17), &spi_config)?;

    // Pixels are batched here before each SPI write. One buffer per panel:
    // `SpiInterface` borrows it for as long as the display lives.
    let mut credit_buffer = [0_u8; 512];
    let mut status_buffer = [0_u8; 512];

    // Both entries have the same type — `PinDriver` erases the pin it drives,
    // and both devices borrow the same `SpiDriver`. That's what lets the draw
    // loop below iterate them.
    let mut displays = [
        Builder::new(
            ST7789,
            SpiInterface::new(credit_spi, PinDriver::output(pins.gpio22)?, &mut credit_buffer),
        )
        // IPS ST7789 panels show a negative image without this.
        .invert_colors(ColorInversion::Inverted)
        .reset_pin(PinDriver::output(pins.gpio23)?)
        .init(&mut Ets)
        .map_err(|e| Error::Panel(format!("init panel 0: {e:?}")))?,
        Builder::new(
            ST7789,
            SpiInterface::new(
                status_spi,
                PinDriver::output(pins.gpio18)?,
                &mut status_buffer,
            ),
        )
        .invert_colors(ColorInversion::Inverted)
        .reset_pin(PinDriver::output(pins.gpio33)?)
        .init(&mut Ets)
        .map_err(|e| Error::Panel(format!("init panel 1: {e:?}")))?,
    ];

    // Black over the whole RAM: every row the glass can show gets written,
    // so no power-on noise survives outside the visible window.
    for (n, display) in displays.iter_mut().enumerate() {
        display
            .clear(Rgb565::BLACK)
            .map_err(|e| Error::Panel(format!("clear panel {n}: {e:?}")))?;
    }

    // `ReusedBuffer`: each panel's RAM keeps its last frame, so Slint only
    // redraws what changed.
    let windows: [Rc<MinimalSoftwareWindow>; PANELS] =
        std::array::from_fn(|_| MinimalSoftwareWindow::new(RepaintBufferType::ReusedBuffer));
    for window in &windows {
        window.set_size(PhysicalSize::new(WIDTH.into(), HEIGHT.into()));
    }
    slint::platform::set_platform(Box::new(Board {
        windows: windows.clone(),
        handed_out: Cell::new(0),
        start: Instant::now(),
    }))
    .map_err(|e| Error::Ui(format!("platform: {e:?}")))?;

    // Construction order is the wiring: the first UI built takes `windows[0]`,
    // which the loop pairs with `displays[0]`. Swap these two blocks and the
    // screens swap panels, silently — Slint gives no other handle here.
    let credit = ui::CreditScreen::new().map_err(|e| Error::Ui(format!("create credit: {e}")))?;
    credit
        .show()
        .map_err(|e| Error::Ui(format!("show credit: {e}")))?;

    let status = ui::StatusScreen::new().map_err(|e| Error::Ui(format!("create status: {e}")))?;
    status
        .show()
        .map_err(|e| Error::Ui(format!("show status: {e}")))?;

    let mut lit = false;

    loop {
        slint::platform::update_timers_and_animations();

        for (window, display) in windows.iter().zip(displays.iter_mut()) {
            draw(window, display)?;
        }

        if !lit {
            // The pass above drew every panel in full, so none shows garbage.
            for backlight in &mut backlights {
                backlight.set_high()?;
            }
            lit = true;
            info!("first frame drawn on {PANELS} panels");
        }

        // Animations need frames; otherwise idle at ~60 Hz polling.
        if !windows.iter().any(|window| window.has_active_animations()) {
            FreeRtos::delay_ms(16);
        }
    }
}
