[package]
name        = "spider-core"
description = "Hardware-independent logic for spider."

version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
edition.workspace      = true
rust-version.workspace = true

[dependencies]
thiserror = { version = "2.0.19", default-features = false }

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest            = "0.26"

[lints]
workspace = true
