[build]
target = "riscv32imafc-esp-espidf"

[target.riscv32imafc-esp-espidf]
linker    = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]
runner    = "espflash flash --monitor"

[env]
MCU                        = "esp32p4"
ESP_IDF_TOOLS_INSTALL_DIR  = "fromenv"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }
ESP_LOG                    = "info"

[unstable]
build-std = ["std", "panic_abort"]
